Apps/shop/urls.py
""" Shop Urls """

#Django
from django.urls import path
from Apps.shop import views
from django.urls import include, path


# Django Rest Framwork
from rest_framework import routers


urlpatterns = [
    path(
        route='', 
        view=views.ProductView.as_view(),
        name='product'
    ),
    
    path(
        route='cart/',
        view=views.CartView.as_view(),
        name='cart'
    ),

    path(
        route='cart/add/<int:id>/',
        view=views.AddProductCart.as_view(),
        name='add_cart'
    ),

    path(
        route='cart/delete/<int:id>/',
        view=views.DeleteProductCart.as_view(),
        name='delete_cart'
    ),

    path(
        route="cart/buy/<int:id>/",
        view=views.ComprarProducto.as_view(),
        name="buy"
    ),

    path(
        route="cart/succefully_buy/",
        view=views.CompraExitosa.as_view(),
        name="succefully_buy"
    ),
]

PruebaDRF/urls.py
from django.urls import include, path
from django.contrib import admin
from rest_framework import routers
from Apps.shop import views
from django.conf import settings
from django.conf.urls.static import static


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [

    #admin URLS
    path('admin/', admin.site.urls),

    #Local URLS
    path('shop/', include(('Apps.shop.urls', 'Apps.shop'),  namespace='shop')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/profile/models.py
""" Users Models """

from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    """ Modelo del Perfil """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    #el carro se guarda tipo json pero en strig despues cuando traigo el dato lo parseo
    cart = models.CharField(default='{"cart": []}', max_length=255)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Return username """
        return self.user.username

Apps/shop/models.py
from django.db import models

class Products(models.Model):
    """ Modelo del los Productos """
    
    #nombre
    name= models.CharField(max_length=20)

    #precio
    price = models.FloatField()

    #stock
    stock = models.PositiveIntegerField(default=0) 

    #descripcion
    description = models.TextField()

    #cuando se creo y se modifico
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """ Reuturn product name """
        return self.name

Apps/shop/views.py
""" Users View """
#Django
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from rest_framework import viewsets, permissions
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response

#Serializers
from Apps.shop.serializers import UserSerializer, ProductSerializer, CartSerializer

#Locals Models
from Apps.shop.models import Products
from Apps.profile.models import Profile

#Utilities
import json


class UserViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class ProductViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    """ User Detail view """
    queryset = Products.objects.all()
    serializer_class = ProductSerializer


class CartViewSet(LoginRequiredMixin, viewsets.ModelViewSet):
    """ CArt Detail view """
    queryset = Profile.objects.all()
    serializer_class = CartSerializer


class ProductView(LoginRequiredMixin, APIView):
    """ Lista de los productos """
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'shop/products.html'
    
    def get(self, request):
        #obtengo los todos los productos disponibles
        queryset = Products.objects.all()

        serializer = ProductSerializer(queryset, many=True)

        #retorno los datos
        return Response({'serializer': serializer.data })


class CartView(LoginRequiredMixin, APIView):
    """ Vista del Carro"""
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'cart/cart.html'

    def get(self, request):
        """ Ver los productos que 
            estan en el carro del perfil
            que esta logeado """
        
        #traigo los datos del perfil
        queryset = Profile.objects.get(user=self.request.user)
        #parceo el carro que esta en string
        data = json.loads(queryset.cart)

        queryset.cart = []
        #compruebo que el carro tenga productos
        if data["cart"]:
            for item in data["cart"]:
                product = Products.objects.get(id=item['id'])
                product.quantity = item['quantity']
                serializer = ProductSerializer(product)
                queryset.cart.append(product)

        #retorno los datos con los productos
        return Response({'queryset': queryset})

class AddProductCart(LoginRequiredMixin, APIView):
    """ Añade un producto a carro del usuario """

    def post(self, request, id):
        #traigo el carro del perfil
        queryset = Profile.objects.get(user=self.request.user)
        
        data = json.loads(queryset.cart)

        check_id = False
        #compruebo que el producto agregado no es en el carro
        for product in data["cart"]:
            if product["id"] == id:
                check_id = True
                break
                
        if not check_id:
            #agrego el id del producto
            quantity = request.POST["quantity"]
            new_product = {"id": id, "quantity": int(quantity)}
            data["cart"].append(new_product)

            #guardo los datos
            queryset.cart = str(data).replace("'", '"')
            queryset.save()
        
        #retorno para la pagina de productos
        return redirect('shop:cart')

class DeleteProductCart(LoginRequiredMixin, APIView):
    """ Eliminar un producto del carro del usuario """
    
    def post(self, request, id):
        #traigo el carro del perfil
        queryset = Profile.objects.get(user=self.request.user)
        
        #saco el id del producto que se quiere eliminar
        data = json.loads(queryset.cart)

        for product in data["cart"]:
            if product["id"] == id:
                data["cart"].remove(product)

        #guardo los datos
        queryset.cart = str(data).replace("'", '"')
        queryset.save()
        
        #retorno hacia la pagina del carro
        return redirect('shop:cart')


class ComprarProducto(LoginRequiredMixin, APIView):
    """ Hacer la compra de los productos que estan en el carro """

    def post(self, request, id):
        #traigo el carro del perfil
        queryset = Profile.objects.get(user=self.request.user)
        data = json.loads(queryset.cart)

        if data["cart"]:
            for product_data in data["cart"]:
                product = Products.objects.get(id=product_data["id"])
                product.stock = product.stock - product_data["quantity"]
                product.save()
            
            queryset.cart = '{"cart": []}'
            queryset.save()
        
        return redirect('shop:succefully_buy')

class CompraExitosa(LoginRequiredMixin, APIView):
    "Mostrar mensaje que la compra fue hecha"
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'cart/succefully_buy.html'

    def get(self, request):
        return Response({"data": request})
        





        

        

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  {% block head_content %}
  {% endblock  %}

  {% load static %}

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">

</head>

<body>
  <!-- Nav bar-->
  {% include 'nav.html' %}  

  <!-- Page Content -->
  <div class="container">
    {% block container %}
    {% endblock  %}
  </div>
  <!-- /Page Content-->


  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
  </footer>
  <!-- /Footer -->


  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>

templates/cart/cart.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Cart Shop</title>
{% endblock  %}

{% block container %}
    <div class="row mt-5">
        {% if queryset.cart%}
            {% for product in queryset.cart %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <img class="card-img-top" src="http://placehold.it/700x400" alt="">
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#{{product.name}}">{{ product.name }}</a>
                            </h4>
                            <h5>${{ product.price }} - (Quantity: {{product.quantity}})</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer">
                            <form action="{% url 'shop:delete_cart' product.id %}" method='POST'>
                                {% csrf_token %}
                                <button class='btn btn-danger btn-dark'> delete </button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
             <h1 class="col text-center" style="height: 74vh;">This cart is Empty</h1>
        {% endif %}
    </div>
    {% if queryset.cart %}
        <div class="row">
            <div class="col pt-3 pb-3">
                <form method="POST" action="{% url 'shop:buy' request.user.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger col-8 offset-2"> Buy </button>
                </form>
            </div>
        </div>
   {% endif %}
{% endblock  %}

templates/cart/succefully_buy.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Thanks for you buy!!</title>
{% endblock %}

{% block container %}
    <div class="row">
        <h1 class="col-4 offset-4">Thanks for you buy!!</h1>
    </div>
{% endblock %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Tecno Shop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:product' %}">Shop
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:cart' %}">Cart</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

templates/shop/products.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Shop</title>
{% endblock  %}

{% block container %}
    <div class="row">
        <div class="row mt-5">
            {% for product in serializer %}
                {% if product.stock > 0 %}
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#{{product.name}}">{{ product.name }}</a>
                                </h4>
                                <h5>${{ product.price }} - (In stock: {{product.stock}})</h5>
                                <p class="card-text">{{ product.description }}</p>
                            </div>
                            <div class="card-footer">
                                <form action="{% url 'shop:add_cart' product.id  %}" method='POST'>
                                    {% csrf_token %}
                                    <input type="number" value="1" min="1" max={{product.stock}} class='btn border-dark mr-5' name='quantity'>
                                    <button class='btn btn-danger btn-dark'> add to cart </button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}    
            {% endfor %}
        </div>
    </div>
{% endblock  %}